distancia = float(input("Ingrese la distancia del recorrido (km): "))
tiempo = float(input("Ingrese el tiempo del recorrido (horas): "))
print("Suma (distancia + tiempo)")
print(distancia, "+", tiempo, distancia + tiempo)
print("Resta (distancia - tiempo)")
print(distancia, "-", tiempo, distancia - tiempo)
print("Multiplicacion (distancia * 2 viajes)")
print(distancia, "*", 2, distancia * 2)
print("Division (distancia / tiempo = velocidad promedio)")
print(distancia, "/", tiempo, distancia / tiempo)
print("Modulo (distancia % 5 = residuo)")
print(distancia, "%", 5, distancia % 5)
print("Exponente (tiempo ** 2)")
print(tiempo, "**", 2, tiempo ** 2)
