print("operadores de comparacion")

numero1=float(input("primer número: "))
numero2=float(input("segundo número: "))
print(numero1,"==",numero2,numero1+numero2)
print(numero1,"!=",numero2,numero1-numero2)
print(numero1,">",numero2,numero1*numero2)
print(numero1,"<",numero2,numero1/numero2)
print(numero1,">=",numero2,numero1%numero2)
print(numero1,"<=",numero2,numero1**numero2)
